name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run linter (if configured)
        working-directory: ./backend
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run unit tests
        working-directory: ./backend
        run: npm run test:unit

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:integration

      - name: Run all tests with coverage
        working-directory: ./backend
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage/lcov.info
          flags: backend
          name: backend-coverage

      - name: Generate coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          jacoco-csv-file: backend/coverage/lcov.info

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./backend/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run security audit
        working-directory: ./backend
        run: npm audit --audit-level=moderate

      - name: Check for outdated dependencies
        working-directory: ./backend
        run: npm outdated || true
